In [1]:
import numpy as np

In [2]:
m=np.random.rand(3,4)

In [3]:
m

array([[0.90815145, 0.82063046, 0.70477845, 0.57575478],
       [0.14002066, 0.46640424, 0.46317273, 0.31645876],
       [0.31860901, 0.85617484, 0.44465402, 0.19993451]])

In [4]:
m[1,1]

0.46640424465636876

In [5]:
m[1]

array([0.14002066, 0.46640424, 0.46317273, 0.31645876])

In [6]:
m[1,2]

0.46317272946195476

In [7]:
m*[2,-1,1,4]

array([[ 1.8163029 , -0.82063046,  0.70477845,  2.30301912],
       [ 0.28004131, -0.46640424,  0.46317273,  1.26583505],
       [ 0.63721801, -0.85617484,  0.44465402,  0.79973803]])

In [8]:
m>2 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [9]:
l=list(range(4))

In [10]:
l


[0, 1, 2, 3]

In [11]:
l=[1]

In [12]:
l

[1]

In [13]:
m+'str'

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

In [16]:
a = np.array([2,3]) 

In [17]:
a

array([2, 3])

In [18]:
b = np.array([4,5])
b

array([4, 5])

In [19]:
a-b

array([-2, -2])

In [20]:
b-1

array([3, 4])

In [21]:
b+1

array([5, 6])

In [22]:
b-a

array([2, 2])

In [24]:
k = (b-a)**2

In [26]:
k = k.sum()

In [27]:
k

8

In [28]:
k**0.5

2.8284271247461903

In [29]:
np.sqrt(k)

2.8284271247461903

In [31]:
marks = [[23,25,25,26],
         [22,22,23,21],
         [15,18,21,16]]

In [32]:
marks = np.array(marks)

In [33]:
marks

array([[23, 25, 25, 26],
       [22, 22, 23, 21],
       [15, 18, 21, 16]])

In [34]:
maths = marks[:,2]

In [35]:
maths

array([25, 23, 21])

In [36]:
maths = marks[:,2]+2

In [37]:
marks[:,2] = maths

In [38]:
marks

array([[23, 25, 27, 26],
       [22, 22, 25, 21],
       [15, 18, 23, 16]])

In [39]:
marks.sum(axis=1)

array([101,  90,  72])

In [40]:
marks.sum(axis=1)[0]

101

In [41]:
marks.sum(axis=0)

array([60, 65, 75, 63])

In [42]:
marks.max()

27

In [43]:
marks.mean()

21.916666666666668

In [44]:
marks.min(axis=1)

array([23, 21, 15])

In [46]:
marks.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [47]:
a

array([2, 3])

In [48]:
a[1]

3

In [49]:
a[1]=a[1]+3

In [50]:
a[1]

6

In [51]:
a

array([2, 6])

In [52]:
b

array([4, 5])

In [61]:
def distance(c,d):
    e=(c-d)**2
    e=e.sum()
    e=np.sqrt(e)
    return e

In [62]:
distance(a,b)

2.23606797749979

In [63]:
## Boolean Indexing

In [64]:
a=np.arange(10)

In [65]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
bs=a>2

In [68]:
bs

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [69]:
a[bs]

array([3, 4, 5, 6, 7, 8, 9])

In [70]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [82]:
c1=a>2
c2=a<8
cf= c1 & c2

In [83]:
a[cf]

array([3, 4, 5, 6, 7])

In [85]:
a[(a>2) & (a<8)]

array([3, 4, 5, 6, 7])

In [86]:
marks

array([[23, 25, 27, 26],
       [22, 22, 25, 21],
       [15, 18, 23, 16]])

In [87]:
c=marks>=25

In [88]:
c

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [89]:
marks[c]

array([25, 27, 26, 25])

In [90]:
marks[:,0]>20

array([ True,  True, False])

In [91]:
marks[marks[:,0]>20]

array([[23, 25, 27, 26],
       [22, 22, 25, 21]])

In [94]:
marks[[True,True,False], [True,True,False,False]]

array([23, 22])